version: '3.1'

services:
  delivery_restaurant_site:
    build: .
    ports:
      - "5000:5000"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${SQLALCHEMY_DATABASE_PASSWORD}

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1