version: '3.1'

services:
  delivery_restaurant_site:
    build: .
    ports:
      - "5000:5000"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${SQLALCHEMY_DATABASE_PASSWORD}

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

  rabbit_mq:
    hostname: rabbit_mq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: .env

  celery_worker:
    build: .
    command: celery -A celery_task.celery worker --loglevel=info --pool=solo -B
    environment:
      - rabbit_host=rabbit_mq