"""edit field name

Revision ID: 1a577c65e749
Revises: 38e09e494a2f
Create Date: 2023-08-21 16:29:41.388852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1a577c65e749'
down_revision: Union[str, None] = '38e09e494a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('test_field1', sa.String(length=255), nullable=True))
    op.drop_column('category', 'test_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('test_field', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_column('category', 'test_field1')
    # ### end Alembic commands ###
