"""add secondary test field

Revision ID: eeb146f550bb
Revises: 1a577c65e749
Create Date: 2023-08-21 16:33:21.803884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eeb146f550bb'
down_revision: Union[str, None] = '1a577c65e749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('test_field', sa.String(length=255), nullable=True))
    op.add_column('category', sa.Column('test_field2', sa.String(length=255), nullable=True))
    op.drop_column('category', 'test_field1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('test_field1', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_column('category', 'test_field2')
    op.drop_column('category', 'test_field')
    # ### end Alembic commands ###
